# Generated by Django 5.1.7 on 2025-03-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(blank=True, help_text='Nombre de usuario que creó el análisis', max_length=150, null=True, verbose_name='Nombre de Usuario')),
                ('email_usuario', models.EmailField(blank=True, help_text='Email del usuario que creó el análisis', max_length=254, null=True, verbose_name='Email del Usuario')),
                ('url_propuesta', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Propuesta')),
                ('contenido', models.TextField(help_text='Descripción detallada del análisis de la propuesta', verbose_name='Contenido del Análisis')),
                ('prompts_utilizados', models.JSONField(blank=True, help_text='Registro de prompts utilizados en el análisis', null=True, verbose_name='Prompts Utilizados')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('REVISADO', 'Revisado'), ('EN_REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True, verbose_name='Palabras Clave')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_propuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Análisis de Propuesta',
                'verbose_name_plural': 'Análisis de Propuestas',
                'ordering': ['-fecha_analisis'],
                'indexes': [models.Index(fields=['usuario', 'fecha_analisis'], name='webapp_anal_usuario_ce26c0_idx'), models.Index(fields=['estado'], name='webapp_anal_estado_2e87e0_idx')],
            },
        ),
    ]
