# Generated by Django 5.1.7 on 2025-03-16 01:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_analisispropuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analisispropuesta',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='perfilprofesional',
            name='deleted_on',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AlterField(
            model_name='analisispropuesta',
            name='prompts_utilizados',
            field=models.JSONField(blank=True, help_text='Registro de prompts utilizados en el análisis (formato JSON)', null=True, verbose_name='Prompts Utilizados (JSON)'),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('deleted_on', models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=255, verbose_name='Objetivo del Prompt')),
                ('texto', models.TextField(verbose_name='Texto del Prompt')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Versión')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('REVISADO', 'Revisado'), ('EN_REVISION', 'En Revisión'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('etiquetas', models.JSONField(blank=True, null=True, verbose_name='Etiquetas')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_creados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('autor_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.autorinfo', verbose_name='Información de Autor')),
                ('especialidades', models.ManyToManyField(blank=True, to='webapp.especialidad', verbose_name='Especialidades')),
                ('rol_ia', models.ForeignKey(blank=True, help_text='Rol que debe asumir la IA al utilizar este prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_con_este_rol', to='webapp.rol', verbose_name='Rol de IA Asignado')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, help_text='Fecha y hora en que el objeto fue eliminado lógicamente.', null=True, verbose_name='Fecha de eliminación')),
                ('version', models.CharField(max_length=20, verbose_name='Versión')),
                ('texto_anterior', models.TextField(verbose_name='Texto Anterior')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_modificaciones', to='webapp.prompt', verbose_name='Prompt')),
            ],
            options={
                'verbose_name': 'Historial de Modificación',
                'verbose_name_plural': 'Historiales de Modificación',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.AddField(
            model_name='analisispropuesta',
            name='prompts',
            field=models.ManyToManyField(blank=True, related_name='analisis_propuestas', to='webapp.prompt', verbose_name='Prompts Utilizados'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['objetivo'], name='webapp_prom_objetiv_7a1e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['autor', 'fecha_creacion'], name='webapp_prom_autor_i_1b4485_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['version'], name='webapp_prom_version_da46dd_idx'),
        ),
    ]
