# Generated by Django 5.1.7 on 2025-03-16 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_autorinfo_analisispropuesta_deleted_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol que puede asumir la IA', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del rol de IA', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rol de IA',
                'verbose_name_plural': 'Roles de IA',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='prompt',
            name='rol_ia',
            field=models.ForeignKey(blank=True, help_text='Rol que debe asumir la IA al utilizar este prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_con_este_rol', to='webapp.rolia', verbose_name='Rol de IA Asignado'),
        ),
    ]
