# Generated by Django 5.1.7 on 2025-03-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rolia_alter_prompt_rol_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas asociadas al prompt', verbose_name='Etiquetas'),
        ),
    ]
