# Generated by Django 5.1.7 on 2025-03-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_prompt_formato_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisispropuesta',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título descriptivo de la propuesta', max_length=255, null=True, verbose_name='Título de la Propuesta'),
        ),
    ]
